obj-$(CONFIG_OPPO_COMMON_SOFT)	+=  oppo_project/
obj-$(CONFIG_OPPO_DEVICE_IFNO)	+=  oppo_devinfo/
obj-$(CONFIG_OPPO_DEBUG_ASSERT)	+=  oppo_trace/
obj-$(CONFIG_RECORD_MDMRST)     +=  oppo_mdmrst/

#ifdef VENDOR_EDIT
#//Chao.zeng@PSW.BSP.Sensor, 2019/08/20, Add for wise light
obj-y     +=  oppo_als_cali_value/
#endif /* VENDOR_EDIT */
